Repository creekorful/trandoshan, pull requests merged in 2020-09, with the labels that each got.

#18 Java options fix in docker-compose.yml.
  deployments/docker/docker-compose.yml
Labels: bug

#24 New architecture
  .dockerignore
  README.md
  api/api.go
  build/docker/Dockerfile.tdsh-api
  build/docker/Dockerfile.tdsh-crawler
  build/docker/Dockerfile.tdsh-extractor
  build/docker/Dockerfile.tdsh-scheduler
  build/docker/Dockerfile.trandoshanctl
  cmd/tdsh-extractor/tdsh-extractor.go
  cmd/trandoshanctl/trandoshanctl.go
  deployments/docker/docker-compose.yml
  docs/architecture.md
  go.mod
  go.sum
  internal/api/api.go
  internal/api/api_test.go
  internal/crawler/crawler.go
  internal/extractor/extractor.go
  internal/extractor/extractor_test.go
  internal/feeder/feeder.go
  internal/messaging/messaging.go
  internal/persister/persister.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/trandoshanctl/trandoshanctl.go
  internal/util/http/client.go
  internal/util/logging/log.go
  internal/util/nats/message.go
  internal/util/nats/nats.go
  internal/util/nats/subscriber.go
  pkg/proto/proto.go
  scripts/build.sh
  scripts/stop.sh
Labels: documentation, enhancement

#30 Implement API authentication
  .github/workflows/ci.yml
  .gitignore
  api/api.go
  deployments/docker/docker-compose.yml
  go.mod
  go.sum
  internal/api/api.go
  internal/api/api_test.go
  internal/api/rest.go
  internal/api/rest_test.go
  internal/api/service.go
  internal/api/service_test.go
  internal/crawler/crawler.go
  internal/crawler/crawler_test.go
  internal/database/database.go
  internal/extractor/extractor.go
  internal/extractor/extractor_test.go
  internal/logging/log.go
  internal/logging/log_test.go
  internal/messaging/message.go
  internal/messaging/messaging.go
  internal/messaging/publisher.go
  internal/messaging/subscriber.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/trandoshanctl/trandoshanctl.go
  internal/util/api.go
  internal/util/nats.go
  internal/util/nats/nats.go
  internal/util/nats/subscriber.go
Labels: enhancement
